name : Excel file automation with python

on : 
  schedule : 
    - cron : '0/5 * * * *'
jobs : 
  update_commit : 
    runs-on : windows_latest
    steps : 
       - name : checking the code
         uses : actions/checkout@v2
       - name : Python 
         uses: actions/setup-python@v2
         with : 
            python-version : '3.x'
       - name : library installation 
         run : |
          pip install gitpython openpyxl datetime pytz
       - name : automation
         run: python commit_excel_file.py  
            

   
