name : Excel file automation with python

on : 
   push : 
      paths :
       - 'file_test/**'
      branches : 
       - main 
jobs : 
  update_commit :
    runs-on : ubuntu-latest
    steps : 
       - name : checking the code
         uses : actions/checkout@v2
       - name : Python 
         uses: actions/setup-python@v2
         with : 
            python-version : '3.x'
       - name : library installation 
         run : |
          python -m pip install --upgrade pip
          pip install gitpython openpyxl datetime pytz pandas
       - name : automation
         run: python file_test/auto.py  
       - name : excel file artifacts
         uses : actions/upload-artifact@v4
         with:
            name: commits_list
            path: C:/Users/se93297/Desktop/TMP102-Driver-main/file_test/commits_list.xlsx

            

   
