name: Notify for a commit done by someone

on:
  push:
    branches:
      - main

jobs:
  notification_commit:
    name: notif_commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit comment
        uses: actions/github-script@v6
        with:
          script: |
            const ACTOR = github.actor;
            const SHA = github.sha;
            const message = github.event.workflow_run.head_commit;
            const repoOwner = github.context.repo.owner;
            const repoName = github.context.repo.repo;
            const commitURL = `https://github.com/${repoOwner}/${repoName}/commit/${SHA}`;

            await github.rest.repos.createCommitComment({
              owner: repoOwner,
              repo: repoName,
              commit_sha: SHA,
              body: `New commit by **${ACTOR}**\n\nCommit message: **${message}**\n\n[View Commit](${commitURL})`
            });
